language: node_js
sudo: required
node_js:
- '4.2'
before_install:
- cp ci/travis-ci.sh $HOME/
- chmod +x $HOME/travis-ci.sh
- $HOME/travis-ci.sh before-install
before_script:
- $HOME/travis-ci.sh before-script
script:
- $HOME/travis-ci.sh script
after_script:
- $HOME/travis-ci.sh after-script
after_success:
- $HOME/travis-ci.sh after-success
before_deploy:
- $HOME/travis-ci.sh before-deploy
after_deploy:
- $HOME/travis-ci.sh after-deploy
cache:
  directories:
  - node_modules
notifications:
  irc:
  - chat.freenode.net#kalabox
  email:
    recipients:
    - mike@kalabox.io
    - riley@kalabox.io
    on_success: always
deploy:
  provider: npm
  email: mike@kalamuna.com
  api_key:
    secure: LqETVZKmboyL3rFtpENXSR8oAN4P5KZHh9XtUambSRXEWkWO2vfyfjjBPZfgll2XdvFikCR2ymujbl4bpnPzY2gyGtGm6wsL0ngCCtzs/mIF5JuKU6v/lO0dKPyj6PC+CB3ZY32Ax4HjsWIKw9v+On/kdz1PimkYWH0fgtrnXkoTs01NgTp1l3c1ASrqjtRjmTYWgsYDHRGKUukYH+wZSSTj4bfln0UcOr907Qzsj1oKWCyK5Hc0InWO4TCrULJa4F6qG70WNnStgbSkz010vutIOtmk11HgDzbaLbetEbF5KNv59jED2WY3/mJbjK3l2vrObM1NG09Je0xKh7fcadENrFTKaLXjxgy0TFOGih6M9qu455/pi68f76tI3d6AcLj9jhylyrYcqpWWyHQfhlluRC3g4YF4+HDh5dG5gqUD5TxMj/r8P2UG8BjlS/Ytn0eYxJsJ9l8g5OdBx7jP0iXArtIyPQeNkhXlUS9aumLufxgOmCrIX2CZTHF97GxosD6nNoYTd7ADfwl6Z5ByucDRDQAycBoMO6ALjM3rIu/WgNg8yr/+jj8DqikW5ye6mnVa03wSOSShfu3VvIA2UrbTW4FU5/H/oNM+BrkUldg+w7rl3LxQSO/fA38Vre1DEdveOomxRMEjNJKmhE1yn9zRE0Zb0wb+yfQOfCFYkuw=
  on:
    tags: true
    branch: v0.12
    repo: kalabox/kalabox-app-pantheon
env:
  global:
    - secure: HgOgBMSQwxAflHC9mP57fsUYBnHPpJgtLD+lTC/852uLPvs4YiL01qPd/TkRS4QsyUmtWADfbuHJ7EXvkMoMjg4jKJcWhpd01bUYmrMzFUWhJp3nqjuipZaGkxsn3cqFtpSh3hSuuC+GjK0wAs4O8Uh77cQ4ZF+qSB4rlKjc9uJoANmFv1GauFjdpMqXAadqLcRyf+zu4UYcSjO1Eo0cgHBvVHmJ5M1GLlFiOXYIAjo6MLOWz0pVvOgzE9PHglKrKq879frdSrNtvqctV4Hp1o25bdafLigeYoQDnhASLpg6rNRVDLsDECdStL0znLAqlNVXKpsOfCHJge5O8tYoa6QPN4aYR/xL5Gt8/Oz7JcJfFI/rIK4zcmRW5j2wfatHzpYM2lY5WlGEAFg3yA2ZPS8hIESWsFtG0UY136WcXzgEoHSRYCzCYLJ153KsAGVugveO7+ALk8uiutvzdxK457Gq46jnh/aG/uV0pLjCwHYPuZ4Hv8xSA02HS/8SoPEnDnHRztEglP9jPEq/xWVJedovzBwBifoa7uwj0SxbsyUI5vhDkZ38CNkXToS2v3rblOZxhKOiDDAkwTaDn9MH+0tL5/2IhIprOKCWTTd6G390eRFp5QwHPrLwVLjyTOZRmXUwgzjllQqe8gwfMnPCvcINPiZIHABy7kz8+MeWmOY=
    - DOCKER_HOST: tcp://10.13.37.100:2375
