data:
  image: busybox
  volumes:
    - /media
    - /certs
    - /sql
    - /code
    - /backups
appserver:
  #image: kalabox/pantheon-appserver:$KALABOX_IMG_VERSION
  build: ./dockerfiles/pantheon-appserver
  hostname: $KALABOX_APP_HOSTNAME
  ports:
    - "8888"
  volumes:
    - $KALABOX_APP_ROOT_BIND:/src:rw
  volumes_from:
    - data
  links:
    - db:database
  environment:
    TERM: xterm
    DOMAIN: $KALABOX_DOMAIN
    FRAMEWORK: $KALABOX_APP_PANTHEON_FRAMEWORK
    PHP_VERSION: 53
    DOCROOT: $KALABOX_APP_PANTHEON_DOCROOT
    FILEMOUNT: $KALABOX_APP_PANTHEON_FILEMOUNT
    DRUPAL_HASH_SALT: $KALABOX_APP_PANTHEON_DRUPAL_HASH_SALT
    DB_HOST: $KALABOX_APP_PANTHEON_DB_HOST
    DB_PORT: $KALABOX_APP_PANTHEON_DB_PORT
    DB_USER: $KALABOX_APP_PANTHEON_DB_USER
    DB_PASSWORD: $KALABOX_APP_PANTHEON_DB_PASSWORD
    DB_NAME: $KALABOX_APP_PANTHEON_DB_NAME
    PANTHEON_ACCOUNT: $KALABOX_APP_PANTHEON_PANTHEON_ACCOUNT
    PANTHEON_SITE: $KALABOX_APP_PANTHEON_PANTHEON_SITE
    PANTHEON_SITE_NAME: $KALABOX_APP_PANTHEON_PANTHEON_SITE_NAME
    PANTHEON_ENVIRONMENT: $KALABOX_APP_PANTHEON_PANTHEON_ENVIRONMENT
    PANTHEON_INFRASTRUCTURE_ENVIRONMENT: $KALABOX_APP_PANTHEON_PANTHEON_INFRASTRUCTURE_ENVIRONMENT
    PRESSFLOW_SETTINGS: $KALABOX_APP_PANTHEON_PRESSFLOW_SETTINGS
    BACKDROP_SETTINGS: $KALABOX_APP_PANTHEON_PRESSFLOW_SETTINGS
    CACHE_HOST: $KALABOX_APP_PANTHEON_CACHE_HOST
    CACHE_PORT: $KALABOX_APP_PANTHEON_CACHE_PORT
    CACHE_PASSWORD: $KALABOX_APP_PANTHEON_CACHE_PASSWORD
    PANTHEON_INDEX_HOST: $KALABOX_APP_PANTHEON_PANTHEON_INDEX_HOST
    PANTHEON_INDEX_PORT: $KALABOX_APP_PANTHEON_PANTHEON_INDEX_PORT
    AUTH_KEY: $KALABOX_APP_PANTHEON_AUTH_KEY
    SECURE_AUTH_KEY: $KALABOX_APP_PANTHEON_SECURE_AUTH_KEY
    LOGGED_IN_KEY: $KALABOX_APP_PANTHEON_LOGGED_IN_KEY
    AUTH_SALT: $KALABOX_APP_PANTHEON_AUTH_SALT
    SECURE_AUTH_SALT: $KALABOX_APP_PANTHEON_SECURE_AUTH_SALT
    LOGGED_IN_SALT: $KALABOX_APP_PANTHEON_LOGGED_IN_SALT
    NONCE_SALT: $KALABOX_APP_PANTHEON_NONCE_SALT
db:
  #image: kalabox/pantheon-mariadb:$KALABOX_IMG_VERSION
  build: ./dockerfiles/pantheon-mariadb
  volumes:
    - $KALABOX_APP_ROOT_BIND:/src:rw
  volumes_from:
    - data
edge:
  #image: kalabox/pantheon-edge:$KALABOX_IMG_VERSION
  build: dockerfiles/pantheon-edge
  links:
    - appserver:web
  volumes:
    - $KALABOX_APP_ROOT_BIND:/src:rw
  volumes_from:
    - data
  environment:
    DOMAIN: $KALABOX_DOMAIN
  ports:
    - "80"
    - "443"

#redis:
  #image: kalabox/pantheon-redis:$KALABOX_IMG_VERSION
  #build: dockerfiles/pantheon-redis

#solr:
  #image: kalabox/pantheon-solr:$KALABOX_IMG_VERSION
#  build: dockerfiles/pantheon-solr
